### ISSUE TITLE
MacOS GUI wallet 2.0.1 does not launch under Mojave 10.14

### ISSUE THREAD

**Issue by yidakee** [loki-project/loki-gui#62] opened 2018-12-04 12:29 UTC
Never had a Loki wallet on this Macbook, so nothing was overwritten. Upon giving rights on Preferences -> File Vault - to allow non-verified developer install of loki-wallet-gui.app - it fails to launch. Not even a splash screen.

``` Process:               loki-wallet-gui [41434]
Path:                  /Applications/loki-wallet-gui.app/Contents/MacOS/loki-wallet-gui
Identifier:            com.yourcompany.loki-wallet-gui
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           loki-wallet-gui [41434]
User ID:               501

Date/Time:             2018-12-04 12:24:23.060 +0000
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Anonymous UUID:        34F1D4D9-87F7-A4B3-EA4A-9516CEF617B2

Sleep/Wake UUID:       104088AC-C244-424A-B262-019AD7EBB27B

Time Awake Since Boot: 370000 seconds
Time Since Wake:       340000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/openssl/1.0.2o_2/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/loki-wallet-gui.app/Contents/Frameworks/libssl.1.0.0.dylib
  Reason: image not found

Binary Images:
       0x105771000 -        0x106398ff3 +com.yourcompany.loki-wallet-gui (0) <76D14983-DB9F-3C3C-91E0-C2B439C096D8> /Applications/loki-wallet-gui.app/Contents/MacOS/loki-wallet-gui
       0x1066c8000 -        0x1066edff7 +libboost_serialization.dylib (0) <865B835F-EC22-3194-9F26-E2E4194751C9> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_serialization.dylib
       0x10671c000 -        0x10671effb +libhidapi.0.dylib (0) <CCD38B83-47E5-3919-8D1D-1A680600EA3B> /Applications/loki-wallet-gui.app/Contents/Frameworks/libhidapi.0.dylib
       0x106726000 -        0x106732ff7 +libboost_thread.dylib (0) <EB7D101F-5AA7-3448-8CF4-B49EBB3CC934> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_thread.dylib
       0x10673e000 -        0x106740ff7 +libboost_system.dylib (0) <E3A48A36-0884-3FAC-8147-8B30708814A6> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_system.dylib
       0x106745000 -        0x106749ff7 +libboost_date_time.dylib (0) <E8A2AD6F-2937-3E19-8413-A8E44BD097D0> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_date_time.dylib
       0x106751000 -        0x106760ff7 +libboost_filesystem.dylib (0) <7AC0F22A-278C-3C6A-AEAF-9EF01F812383> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_filesystem.dylib
       0x106768000 -        0x106800fff +libboost_regex.dylib (0) <4C61406E-52D4-3E78-901F-008170CEDCF5> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_regex.dylib
       0x106836000 -        0x106838fff +libboost_chrono.dylib (0) <49D9DCF2-A523-3E19-B5E7-ABEC94D3FAEA> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_chrono.dylib
       0x10683c000 -        0x10686fff7 +libboost_program_options.dylib (0) <8FDAC8A6-2FC3-3B2E-AF4F-5F7CF5E06978> /Applications/loki-wallet-gui.app/Contents/Frameworks/libboost_program_options.dylib
       0x10688d000 -        0x1068ccfff +libssl.1.0.0.dylib (0) <4D343D8E-B72A-38BD-9204-CC0354C0B7F8> /Applications/loki-wallet-gui.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x1068ef000 -        0x106975fdb +libsodium.23.dylib (0) <1A1990C2-1DFE-3767-B304-BEBC2A98F388> /Applications/loki-wallet-gui.app/Contents/Frameworks/libsodium.23.dylib
       0x106987000 -        0x106af7d67 +libcrypto.1.0.0.dylib (0) <4A0A66FE-A6B9-387F-B265-512C91DF46F9> /Applications/loki-wallet-gui.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x106b5f000 -        0x106e3afff +org.qt-project.QtQuick (5.7 - 5.7.1) <5C7562FF-7DDD-3AC0-9DCD-7C4CDC5E3A2B> /Applications/loki-wallet-gui.app/Contents/Frameworks/QtQuick.framework/Versions/5/QtQuick
       0x106f16000 -        0x107238fff +org.qt-project.QtQml (5.7 - 5.7.1) <D1C3B35D-248F-3C31-BE9C-11FC3BB97241> /Applications/loki-wallet-gui.app/Contents/Frameworks/QtQml.framework/Versions/5/QtQml
       0x1072d3000 -        0x1073d7fff +org.qt-project.QtNetwork (5.7 - 5.7.1) <D40D5FDA-FF1E-3AE8-B4CD-D9A0E678898D> /Applications/loki-wallet-gui.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10741a000 -        0x107932ff7 +org.qt-project.QtCore (5.7 - 5.7.1) <A949A510-F55A-3D4B-8851-FCAC13DF963F> /Applications/loki-wallet-gui.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1079e7000 -        0x107e4afff +org.qt-project.QtGui (5.7 - 5.7.1) <61FB743C-29E3-3B69-A210-152ADEF47D33> /Applications/loki-wallet-gui.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x107f3c000 -        0x108437ff7 +org.qt-project.QtWidgets (5.7 - 5.7.1) <6D63465B-172F-32FB-81CB-CE99A282E9E8> /Applications/loki-wallet-gui.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10fb75000 -        0x10fbf36a7  dyld (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> /usr/lib/dyld
    0x7fff374c7000 -     0x7fff374cbfff  com.apple.agl (3.3.2 - AGL-3.3.2) <81130C05-30AD-3BDA-BB9C-72ADDD5FAA2C> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff3b565000 -     0x7fff3b9b4fff  com.apple.CoreFoundation (6.9 - 1555.10) <4A4C87BC-4C8E-392A-ABEE-824D4074C485> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3d716000 -     0x7fff3d71bfff  com.apple.DiskArbitration (2.7 - 2.7) <C53C1905-9BCF-3AE8-8BB3-C8A2C7DB7D25> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff3dfd7000 -     0x7fff3e068fff  com.apple.framework.IOKit (2.0.2 - 1483.201.1) <DA4ED91F-2CC9-3CFD-9200-9D5D31EEE4F3> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff456b4000 -     0x7fff456c3ff3  com.apple.opengl (17.0.37 - 17.0.37) <FA76EAA6-D035-3444-87F5-DD95446D651D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff45884000 -     0x7fff4588eff3  com.apple.pcsc (8.0 - 1) <221F377F-F384-3AE2-8FA2-230C5CEA4A7A> /System/Library/Frameworks/PCSC.framework/Versions/A/PCSC
    0x7fff656f8000 -     0x7fff656f9ff7  libDiagnosticMessagesClient.dylib (107) <C542CB3C-AA44-3D7F-B88C-79CC31B481AB> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff65aaa000 -     0x7fff65aabffb  libSystem.B.dylib (1252.200.5) <D5133811-9D66-3DEB-9521-0A67347C9A54> /usr/lib/libSystem.B.dylib
    0x7fff65ce5000 -     0x7fff65cf5ff3  libbsm.0.dylib (39.200.18) <5E5098D0-F7B2-32A1-8038-E709F6718D4E> /usr/lib/libbsm.0.dylib
    0x7fff65d05000 -     0x7fff65d5cff7  libc++.1.dylib (400.9.4) <D4AB366F-48A9-3C7D-91BD-41198F69DD57> /usr/lib/libc++.1.dylib
    0x7fff65d5d000 -     0x7fff65d72fff  libc++abi.dylib (400.17) <BA948A32-9024-3E55-98D4-18E31F6AED25> /usr/lib/libc++abi.dylib
    0x7fff66865000 -     0x7fff66865fff  libenergytrace.dylib (17.200.1) <D62ED169-B91C-3CCB-ADF5-E66AE4007B51> /usr/lib/libenergytrace.dylib
    0x7fff669c0000 -     0x7fff66c23ffb  libicucore.A.dylib (62107.0.1) <EAE6FC43-3AD2-3A53-9F7A-4E5E5F66D006> /usr/lib/libicucore.A.dylib
    0x7fff67551000 -     0x7fff67cd7fe7  libobjc.A.dylib (750) <2E868147-8818-359E-8CD7-A8B80665928F> /usr/lib/libobjc.A.dylib
    0x7fff68434000 -     0x7fff68446ffb  libz.1.dylib (70.200.4) <99A3D725-8388-38B4-B66C-5E9006E6F072> /usr/lib/libz.1.dylib
    0x7fff684b7000 -     0x7fff684bbff3  libcache.dylib (81) <FE21A7E9-DBEB-33AC-836B-785AD036ACF4> /usr/lib/system/libcache.dylib
    0x7fff684bc000 -     0x7fff684c6ff3  libcommonCrypto.dylib (60118.200.6) <78093D4F-91DB-35C8-981A-13375778B2E7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff684c7000 -     0x7fff684cefff  libcompiler_rt.dylib (63.4) <A4D9CF37-D076-3CE9-95F1-DA89DA1601B6> /usr/lib/system/libcompiler_rt.dylib
    0x7fff684cf000 -     0x7fff684d8ff3  libcopyfile.dylib (146.200.3) <4BCDADBF-79F5-3829-B47D-64DA0D44BCBF> /usr/lib/system/libcopyfile.dylib
    0x7fff684d9000 -     0x7fff6855dfff  libcorecrypto.dylib (602.200.50) <7AEC5B72-0B92-37E8-808B-6732DB714139> /usr/lib/system/libcorecrypto.dylib
    0x7fff685e3000 -     0x7fff6861dff7  libdispatch.dylib (1008.200.78) <B8962879-AD55-3CF0-9B0A-5F1D57D1E14B> /usr/lib/system/libdispatch.dylib
    0x7fff6861e000 -     0x7fff6864dfff  libdyld.dylib (625.13) <4B16C209-83D4-3817-9B62-C2F7FFB23755> /usr/lib/system/libdyld.dylib
    0x7fff6864e000 -     0x7fff6864effb  libkeymgr.dylib (30) <A73AA788-C35C-3284-BFCA-95B1BBDF0CF3> /usr/lib/system/libkeymgr.dylib
    0x7fff6864f000 -     0x7fff6865bff7  libkxld.dylib (4903.201.2) <EAF1CF8D-3843-33BE-8126-30994685B8F0> /usr/lib/system/libkxld.dylib
    0x7fff6865c000 -     0x7fff6865cff7  liblaunch.dylib (1336.201.2) <43E6698E-155E-3EAE-BAFF-CA5FCB35325C> /usr/lib/system/liblaunch.dylib
    0x7fff6865d000 -     0x7fff68662fff  libmacho.dylib (917) <17BF7038-9C70-3EE1-9E96-3AE10D49669E> /usr/lib/system/libmacho.dylib
    0x7fff68663000 -     0x7fff68665ff3  libquarantine.dylib (86.200.11) <C70DA995-0D6E-302C-A15E-F7F03A3857B4> /usr/lib/system/libquarantine.dylib
    0x7fff68666000 -     0x7fff68667ff3  libremovefile.dylib (45.200.2) <D74A307B-3DC7-3992-B16C-DACB8207BE13> /usr/lib/system/libremovefile.dylib
    0x7fff68668000 -     0x7fff6867fff3  libsystem_asl.dylib (356.200.4) <EC9D8AD4-E5CB-3765-804A-9E1E9DC045D2> /usr/lib/system/libsystem_asl.dylib
    0x7fff68680000 -     0x7fff68680fff  libsystem_blocks.dylib (73) <26419398-C30C-30F1-B656-A92AFA9560F6> /usr/lib/system/libsystem_blocks.dylib
    0x7fff68681000 -     0x7fff68709fff  libsystem_c.dylib (1272.200.26) <3DEEE96E-6DF6-35AD-8654-D69AC26B907B> /usr/lib/system/libsystem_c.dylib
    0x7fff6870a000 -     0x7fff6870dff7  libsystem_configuration.dylib (963.200.27) <02CC3996-B34E-333C-8806-AE2699D34424> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6870e000 -     0x7fff68711ff7  libsystem_coreservices.dylib (66) <254B6849-2C8F-302C-8616-B8324A11AB30> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff68712000 -     0x7fff68718ffb  libsystem_darwin.dylib (1272.200.26) <974E9EF7-DE72-34B7-B056-0A81C10DF8EB> /usr/lib/system/libsystem_darwin.dylib
    0x7fff68719000 -     0x7fff6871fff7  libsystem_dnssd.dylib (878.200.35) <FFC665AA-B257-35AD-BD8B-32FD42C2EEC1> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff68720000 -     0x7fff6876cff3  libsystem_info.dylib (517.200.9) <0707C387-D7DE-372E-8FF1-3DE5C91932D6> /usr/lib/system/libsystem_info.dylib
    0x7fff6876d000 -     0x7fff68794ff7  libsystem_kernel.dylib (4903.201.2) <45FAA4C0-D553-34FD-ADF8-884886AE0D2A> /usr/lib/system/libsystem_kernel.dylib
    0x7fff68795000 -     0x7fff687e0ff7  libsystem_m.dylib (3158.200.7) <43D1796B-954F-37D6-B1AC-9D80DF0655A2> /usr/lib/system/libsystem_m.dylib
    0x7fff687e1000 -     0x7fff68805ff7  libsystem_malloc.dylib (166.200.60) <846F6898-117C-3427-A8FB-3772FFC2410B> /usr/lib/system/libsystem_malloc.dylib
    0x7fff68806000 -     0x7fff68811ffb  libsystem_networkextension.dylib (767.200.40) <F84D5474-4DC1-3E1A-AE00-8CE9593278B4> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff68812000 -     0x7fff68819fff  libsystem_notify.dylib (172.200.21) <BCCB222F-DC64-3954-A836-DCCE6659CA5A> /usr/lib/system/libsystem_notify.dylib
    0x7fff6881a000 -     0x7fff68823fef  libsystem_platform.dylib (177.200.16) <B75B04AD-69FE-3ADE-84D2-C17972FC8F49> /usr/lib/system/libsystem_platform.dylib
    0x7fff68824000 -     0x7fff6882efff  libsystem_pthread.dylib (330.201.1) <87A6B136-E423-3B6D-A58A-137F392D7D9D> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6882f000 -     0x7fff68832ff7  libsystem_sandbox.dylib (851.201.1) <FBA7E09B-F10F-3424-90EA-B4999B7FB461> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff68833000 -     0x7fff68835ff7  libsystem_secinit.dylib (30.200.13) <CBEAB62B-F0A0-342F-9878-CADC14A3CB0D> /usr/lib/system/libsystem_secinit.dylib
    0x7fff68836000 -     0x7fff6883dff7  libsystem_symptoms.dylib (820.207.88) <B6E22FA8-0F7B-36FD-9D99-284056D3CB47> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6883e000 -     0x7fff68853ff7  libsystem_trace.dylib (906.200.86) <7983ED77-18B5-39A5-BE19-AE4F2832ADEA> /usr/lib/system/libsystem_trace.dylib
    0x7fff68855000 -     0x7fff6885affb  libunwind.dylib (35.4) <41222EF6-2233-3CF4-947A-15D48CB8C030> /usr/lib/system/libunwind.dylib
    0x7fff6885b000 -     0x7fff6888bfff  libxpc.dylib (1336.201.2) <0A8747D1-33AA-37E1-B97A-BA9B95FE4E8C> /usr/lib/system/libxpc.dylib

Model: MacBookPro11,1, BootROM MBP111.0146.B00, 2 processors, Intel Core i5, 2,4 GHz, 8 GB, SMC 2.16f68
Graphics: Intel Iris, Intel Iris, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x384B54463531323634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.8f6, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: iPhone, Ethernet, en3
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: iPhone
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2
 ```

**Comment by Doy-lee** [comment] 2018-12-05 02:35
This should be fixed in the newest binaries uploaded. This was caused by a change in the build script requesting the wrongly built version of ssl on our build machine. 

Please reopen if there are any further issues.

**Closed by Doy-lee** 2018-12-05 02:35 UTC
